### ISSUE TITLE
Update documentation to align with a new API shape

### ISSUE THREAD

**Issue by vmpstr** [chrishtr/display-locking#24]
See #15 for discussion.

Basically, the change is from having a lock object that is explicitly committed to an "acquireDisplayLock" which runs a callback, possibly continuing the scheduling via a context, and automatically commits.

**Comment by domenic** [comment]
Please up the priority on this one; when talking to other folks it's hard to tell them what display locking is with an outdated explainer :)

**Comment by vmpstr** [comment]
I'll try to get this done today
